#!/bin/bash

USER_ID="$1"

if [ -z "$USER_ID" ]
then
  echo "You must provide a user ID. Usage: 'delete-user USER_ID'";
  exit 1;
fi

USERNAME=$(echo "SELECT display_name FROM users WHERE user_id='$USER_ID';" | psql -Aqt -U miter miter-test)

if [ -z "$USERNAME" ]
then
  echo "It seems like the user you are trying to delete wasn't found or it has no name. Please, double check the user ID.";
fi

read -p "Are you sure you want to delete user '$USERNAME'? y/n: " -n 1 -r
echo ""  # Add a line break.

# Exit is the reply wasn't: Y or y.
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  exit 1
fi

# Delete the user.
echo "
  DELETE FROM item_associated_people
  WHERE note_id IN (
    SELECT notes_id FROM notes WHERE created_by = '$USER_ID'
  )
  OR summary_item_id IN (
    SELECT summary_item_id FROM summary_items WHERE created_by = '$USER_ID'
  );

  DELETE FROM summary_items WHERE created_by = '$USER_ID';
  DELETE FROM notes WHERE created_by = '$USER_ID';
  DELETE FROM users WHERE user_id = '$USER_ID';
" | psql -Aqt -U miter miter-test && echo "User successfully deleted."
